version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=leave
      - MYSQL_USER=leave
      - MYSQL_PASSWORD=leave
      - MYSQL_DATABASE=leave
    ports:
      - "3306:3306"