server:
  port: 9099
  shutdown: graceful

spring:
  application:
    name: leave
  http:
    encoding.charset: UTF-8
    encoding.force: true

  datasource:
    url: jdbc:mysql://localhost:3306/leave
    username: leave
    password: leave
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true